apiVersion: skaffold/v4beta13
kind: Config
metadata:
  name: civic-grant-agent
build:
  artifacts:
    - image: civic-grant-agent-frontend
      context: frontend
      docker:
        dockerfile: Dockerfile
    - image: civic-grant-agent-backend
      context: .
      docker:
        dockerfile: backend/Dockerfile
  local:
    push: false
deploy:
  kubectl: {}
manifests:
  rawYaml:
    - k8s/deployment.yaml
    - k8s/service.yaml
    - k8s/secret.yaml
portForward:
  - resourceType: service
    resourceName: civic-grant-agent-frontend
    namespace: default
    port: 3000
    localPort: 3000
  - resourceType: service
    resourceName: civic-grant-agent-backend
    namespace: default
    port: 8000
    localPort: 8000
profiles:
  - name: dev
    activation:
      - command: dev
    build:
      artifacts:
        - image: civic-grant-agent-frontend
          context: frontend
          docker:
            dockerfile: Dockerfile
        - image: civic-grant-agent-backend
          context: .
          docker:
            dockerfile: backend/Dockerfile
    deploy:
      kubectl: {}
    manifests:
      rawYaml:
        - k8s/deployment.yaml
        - k8s/service.yaml
        - k8s/secret.yaml
