apiVersion: skaffold/v4beta13
kind: Config
metadata:
  name: backend 
build:
  artifacts:
    - image: civic-grant-agent-backend
      context: .
      docker:
        dockerfile: backend/Dockerfile
manifests:
  rawYaml:
    - k8s/deployment.yaml
    - k8s/service.yaml
    - k8s/secret.yaml
deploy:
  kubectl: {}
portForward:
  - resourceType: service
    resourceName: civic-grant-agent-backend
    port: 8000
    localPort: 8000
profiles:
  - name: cloudrun
    patches:
      - op: remove
        path: /deploy/kubectl
      - op: remove
        path: /portForward
    build:
      googleCloudBuild:
        projectId: "civic-grant-agent-core"
    manifests:
      rawYaml:
        - cloudrun/backend-service.yaml
    deploy:
      cloudrun:
        projectid: "civic-grant-agent-core"
        region: us-central1
---
apiVersion: skaffold/v4beta13
kind: Config
metadata:
  name: frontend
build:
  artifacts:
    - image: civic-grant-agent-frontend
      context: frontend
      docker:
        dockerfile: Dockerfile
manifests:
  rawYaml:
    - k8s/frontend.yaml
deploy:
  kubectl: {}
portForward:
  - resourceType: service
    resourceName: civic-grant-agent-frontend
    port: 3000
    localPort: 3000
profiles:
  - name: cloudrun
    patches:
      - op: remove
        path: /deploy/kubectl
      - op: remove
        path: /portForward
    build:
      googleCloudBuild:
        projectId: "civic-grant-agent-core"
    manifests:
      rawYaml:
        - cloudrun/frontend-service.yaml
    deploy:
      cloudrun:
        projectid: "civic-grant-agent-core"
        region: us-central1