apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: civic-grant-agent-backend
  labels:
    app: civic-grant-agent
    tier: backend
spec:
  template:
    metadata:
      annotations:
        autoscaling.knative.dev/minScale: "0"
        autoscaling.knative.dev/maxScale: "10"
    spec:
      containerConcurrency: 80
      timeoutSeconds: 300
      containers:
      - name: backend
        image: civic-grant-agent-backend
        ports:
        - name: http1
          containerPort: 8000
        env:
        - name: GEMINI_MODEL
          value: "gemini-2.0-flash-exp"
        - name: GOOGLE_API_KEY
          valueFrom:
            secretKeyRef:
              name: GOOGLE_API_KEY
              key: latest
        resources:
          limits:
            cpu: "2"
            memory: 2Gi
  traffic:
  - percent: 100
    latestRevision: true
