apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: civic-grant-agent-frontend
  labels:
    app: civic-grant-agent
    tier: frontend
spec:
  template:
    metadata:
      annotations:
        autoscaling.knative.dev/minScale: "0"
        autoscaling.knative.dev/maxScale: "10"
    spec:
      containerConcurrency: 80
      timeoutSeconds: 300
      containers:
      - name: frontend
        image: civic-grant-agent-frontend
        ports:
        - name: http1
          containerPort: 3000
        env:
        - name: NODE_ENV
          value: "production"
        - name: HOSTNAME
          value: "0.0.0.0"
        - name: NEXT_TELEMETRY_DISABLED
          value: "1"
        - name: NEXT_PUBLIC_API_URL
          value: "https://civic-grant-agent-backend-grsfveacla-uc.a.run.app"
        resources:
          limits:
            cpu: "1"
            memory: 512Mi
  traffic:
  - percent: 100
    latestRevision: true
